### ISSUE TITLE
Just out of interest

### ISSUE THREAD

**Issue by Lwzzzzzz** [cilinyan/LTCA#1]
Is this code prepared for 0.6264 on MeVIS? 🙂

**Comment by cilinyan** [comment]
Yes, if all goes well, the code will be released in April.

**Comment by Lwzzzzzz** [comment]
WoW! It's so amazing, you have achieved about 30% improvement. Looking forward to your paper!

**Comment by cilinyan** [comment]
The competition metric of 0.6264 was achieved using some additional tricks. In our paper, we only reported the metrics obtained without using any additional tricks. Despite this, our method still significantly outperforms the current second place. We also hope to release our code and model weights as scheduled in April. Thank you for your interest!

**Comment by Lwzzzzzz** [comment]
Anyway, congratulations！
